#!/usr/bin/env bash
# This script prints Beest School 10 times and on 9 it prints hi
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ "$i" -eq 9 ]
    then
    echo "Hi"
    fi
    i=$(( i + 1 ))
done
