#!/usr/bin/env bash
# A Bash script that gives you information about the school file
fil="./school"
if [ -e $fil ]; then
   echo "school file exists"
   if [ -s $fil ]; then
      echo "school file is not empty"
   else
      echo "school file is empty"
   fi
   if [ -f $fil ]; then
      echo "school is a regular file"
   fi
else
	echo "school file does not exist"
fi
