#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below
# requirements.
cp /etc/hosts ~/new
sed -i s/^127.*localhost$/127.0.0.2\ localhost/ ~/new
echo "8.8.8.8 facebook.com" >> ~/new
cp -f ~/new /etc/hosts
